# Generated by Django 3.2.6 on 2021-09-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='permissible_cash_difference_minus',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='permissible_cash_difference_plus',
            field=models.BigIntegerField(default=0),
        ),
    ]
