# Generated by Django 3.2.6 on 2021-09-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210910_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='shift_start_time',
            field=models.TimeField(default='09:00:00'),
        ),
    ]
