# Generated by Django 3.2.6 on 2021-08-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210811_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='qwe',
            field=models.ManyToManyField(to='main.Client'),
        ),
    ]
