# Generated by Django 3.2.6 on 2021-08-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_admin_qwe'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='clients',
            field=models.ManyToManyField(blank=True, to='main.Client', verbose_name='clients'),
        ),
    ]
