# Generated by Django 3.2.6 on 2021-08-13 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_admin_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='clients',
        ),
        migrations.AddField(
            model_name='admin',
            name='clients',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.client', verbose_name='clients'),
        ),
    ]
