# Generated by Django 3.2.6 on 2021-08-13 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_auto_20210813_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='clients',
        ),
        migrations.AddField(
            model_name='admin',
            name='clients',
            field=models.ManyToManyField(blank=True, to='main.Client'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
