# Generated by Django 3.2.6 on 2021-08-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_admin_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='clients',
            field=models.ManyToManyField(to='main.Client'),
        ),
    ]
