# Generated by Django 3.2.6 on 2021-10-11 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Additional expense categories',
            },
        ),
        migrations.CreateModel(
            name='Cashbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('index', models.IntegerField(null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'cashboxes',
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('is_accounting_expense', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'expense categories',
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.TextField(max_length=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_start', models.BigIntegerField(default=0)),
                ('cash_end', models.BigIntegerField(default=0)),
                ('noncash_start', models.BigIntegerField(default=0)),
                ('noncash_end', models.BigIntegerField(default=0)),
                ('sales', models.BigIntegerField(default=0)),
                ('cashbox_fact', models.BigIntegerField(default=0)),
                ('cash_refund', models.BigIntegerField(default=0)),
                ('noncash_refund', models.BigIntegerField(default=0)),
                ('cash_income', models.BigIntegerField(default=0, null=True)),
                ('noncash_income', models.BigIntegerField(default=0, null=True)),
                ('shift_income', models.BigIntegerField(default=0, null=True)),
                ('fact', models.BooleanField(default=False)),
                ('cash_difference', models.BigIntegerField(default=0, null=True)),
                ('noncash_difference', models.BigIntegerField(default=0, null=True)),
                ('difference_report', models.TextField(blank=True, default=None, max_length=1000, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('cashbox', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.cashbox')),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('index', models.IntegerField(null=True, unique=True)),
                ('hourly_rate', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, unique=True)),
                ('cash_income', models.IntegerField(blank=True, default=None, null=True)),
                ('noncash_income', models.IntegerField(blank=True, default=None, null=True)),
                ('total_income', models.IntegerField(blank=True, default=None, null=True)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_time', models.BigIntegerField(default=None, null=True)),
                ('break_time', models.BigIntegerField(default=None, null=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.shift')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftTraker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(choices=[(1, 'START'), (2, 'PAUSE'), (3, 'RESUME'), (4, 'STOP')])),
                ('datetime', models.DateTimeField()),
                ('working_time', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.workingtime')),
            ],
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.shifttype'),
        ),
        migrations.AddField(
            model_name='shift',
            name='working_day',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.workingday'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('who', models.CharField(max_length=250)),
                ('whom', models.CharField(max_length=250)),
                ('sum', models.IntegerField()),
                ('comment', models.TextField(blank=True, max_length=500, null=True)),
                ('cashbox', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.cashbox')),
                ('expense_category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.expensecategory')),
                ('shift_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.shifttype')),
                ('working_day', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.workingday')),
            ],
        ),
        migrations.CreateModel(
            name='Bonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_to', models.BigIntegerField()),
                ('rate', models.IntegerField()),
                ('shift_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.shifttype')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_time', models.TimeField(auto_created=True, auto_now_add=True, null=True)),
                ('date', models.DateField(null=True)),
                ('name', models.TextField(blank=True, max_length=500, null=True)),
                ('calculation_formula', models.TextField(blank=True, default=None, null=True)),
                ('sum', models.BigIntegerField(blank=True, null=True)),
                ('additional_expense_category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.additionalexpensecategory')),
            ],
        ),
    ]
