# Generated by Django 3.2.6 on 2021-08-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingday',
            name='shifts_left',
            field=models.IntegerField(),
        ),
    ]
