# Generated by Django 3.2.6 on 2021-08-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbox',
            name='index',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cashbox',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
