# Generated by Django 3.2.6 on 2021-10-11 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_payroll'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payroll',
        ),
    ]
