# Generated by Django 3.2.6 on 2021-08-07 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20210807_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsettings',
            name='tenant',
        ),
    ]
