# Generated by Django 3.2.6 on 2021-08-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_workingday_shifts_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingday',
            name='shifts_left',
        ),
        migrations.AddField(
            model_name='workingday',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
