# Generated by Django 3.2.6 on 2021-08-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20210829_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifttraker',
            name='action',
            field=models.IntegerField(choices=[(1, 'START'), (2, 'PAUSE'), (3, 'RESUME'), (4, 'STOP')], default=1, max_length=1),
        ),
    ]
