# Generated by Django 3.2.6 on 2021-10-11 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '__first__'),
        ('crm', '0003_delete_payroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('from_shift', models.BigIntegerField(default=0)),
                ('from_interest', models.BigIntegerField(default=0)),
                ('paid', models.BigIntegerField(default=0)),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
                ('period', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.payrollperiod')),
            ],
        ),
    ]
