# Generated by Django 3.2.6 on 2021-08-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_shifttraker_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifttraker',
            name='action',
            field=models.IntegerField(choices=[(1, 'START'), (2, 'PAUSE'), (3, 'RESUME'), (4, 'STOP')], default=1),
        ),
    ]
