# Generated by Django 3.2.6 on 2021-08-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_projectsettings_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(choices=[('1', 'Утро'), ('2', 'День'), ('3', 'Ночь')], max_length=1)),
            ],
        ),
    ]
