# Generated by Django 3.2.6 on 2021-08-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20210815_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingday',
            name='cash_income',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='noncash_income',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
