# Generated by Django 3.2.6 on 2021-10-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_payroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='from_interest',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='from_shift',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='paid',
            field=models.FloatField(default=0),
        ),
    ]
