# Generated by Django 3.2.6 on 2021-08-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20210807_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='name',
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('1', 'Утро'), ('2', 'День'), ('3', 'Ночь')], default=1, max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
