# Generated by Django 3.2.6 on 2021-08-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20210807_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
