# Generated by Django 3.2.6 on 2021-08-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_shifttraker_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifttraker',
            name='action',
            field=models.CharField(choices=[('1', 'START'), ('2', 'PAUSE'), ('3', 'RESUME'), ('4', 'STOP')], max_length=1),
        ),
    ]
