# Generated by Django 3.2.6 on 2021-10-14 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '__first__'),
        ('crm', '0007_auto_20211013_1042'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payroll',
            new_name='ShiftPayroll',
        ),
        migrations.RenameModel(
            old_name='PayrollPeriod',
            new_name='ShiftPayrollPeriod',
        ),
    ]
