# Generated by Django 3.2.6 on 2021-08-16 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_expense_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.expensecategory'),
        ),
    ]
