# Generated by Django 3.2.6 on 2021-08-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_expense_expense_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='refund',
            new_name='cash_refund',
        ),
        migrations.AddField(
            model_name='shift',
            name='noncash_refund',
            field=models.IntegerField(null=True),
        ),
    ]
