# Generated by Django 3.2.6 on 2021-08-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20210816_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='cash_refund',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shift',
            name='noncash_refund',
            field=models.IntegerField(default=0),
        ),
    ]
