# Generated by Django 3.2.6 on 2021-09-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_shifttraker_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='cash_difference',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='cash_end',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shift',
            name='cash_income',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='cash_refund',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shift',
            name='cash_start',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shift',
            name='cashbox_fact',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shift',
            name='noncash_difference',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='noncash_end',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shift',
            name='noncash_income',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='noncash_refund',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shift',
            name='noncash_start',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shift',
            name='sales',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_income',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
