# Generated by Django 3.2.6 on 2021-10-22 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '__first__'),
        ('crm', '0009_auto_20211014_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidSalaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('sum', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comment', models.TextField(blank=True, max_length=500, null=True)),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
            ],
        ),
    ]
