# Generated by Django 3.2.6 on 2021-08-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20210816_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='cash_difference',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='cash_income',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='noncash_difference',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='noncash_income',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_income',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
