# Generated by Django 3.2.6 on 2021-08-07 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('crm', '0010_alter_project_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectemployees',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.employee'),
        ),
    ]
