# Generated by Django 3.2.6 on 2021-09-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_expense_cashbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='accounting',
            field=models.BooleanField(default=True),
        ),
    ]
