# Generated by Django 3.2.6 on 2021-08-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20210816_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingday',
            name='cash_income',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='noncash_income',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
