# Generated by Django 3.2.6 on 2021-08-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_workingday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingday',
            name='date',
            field=models.DateField(),
        ),
    ]
