# Generated by Django 3.2.6 on 2021-08-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_auto_20210817_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingday',
            name='revenue',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
