# Generated by Django 3.2.6 on 2021-08-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_alter_workingday_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingday',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
