# Generated by Django 3.2.6 on 2021-08-17 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_workingday_revenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifferenceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(max_length=1000)),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.shift')),
            ],
        ),
    ]
