# Generated by Django 3.2.6 on 2021-09-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_shifttype_hourly_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifttype',
            name='hourly_rate',
            field=models.IntegerField(),
        ),
    ]
