# Generated by Django 3.2.6 on 2021-08-07 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_alter_workingday_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectEmployees',
        ),
    ]
