# Generated by Django 3.2.6 on 2021-09-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_alter_shifttype_hourly_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_to', models.BigIntegerField()),
                ('rate', models.IntegerField()),
            ],
        ),
    ]
