# Generated by Django 3.2.6 on 2021-08-07 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_delete_projectemployees'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectSettings',
            new_name='Options',
        ),
    ]
