# Generated by Django 3.2.6 on 2021-08-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_differencereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='difference_report',
            field=models.TextField(default=None, max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='DifferenceReport',
        ),
    ]
