# Generated by Django 3.2.6 on 2021-08-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_rename_projectsettings_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Options',
            new_name='Parametre',
        ),
    ]
