# Generated by Django 3.2.6 on 2021-09-11 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_bonuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('is_accounting_expense', models.BooleanField(default=True)),
                ('calculation_formula', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.calculationformula')),
            ],
            options={
                'verbose_name_plural': 'Additional expense categories',
            },
        ),
        migrations.CreateModel(
            name='AdditionalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('name', models.TextField(blank=True, max_length=500, null=True)),
                ('sum', models.IntegerField()),
                ('additional_expense_category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.additionalexpensecategory')),
            ],
        ),
    ]
