# Generated by Django 3.2.6 on 2021-08-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_rename_revenue_workingday_total_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='difference_report',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
