# Generated by Django 3.2.6 on 2021-08-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_rename_options_parametre'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametre',
            name='value',
            field=models.CharField(default='', max_length=255),
        ),
    ]
