# Generated by Django 3.2.6 on 2021-08-20 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_alter_shift_difference_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='shift_end_time',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='shift_start_time',
        ),
        migrations.AddField(
            model_name='shift',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ShiftTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timer_type', models.CharField(choices=[('1', 'START'), ('2', 'PAUSE'), ('3', 'RESUME'), ('4', 'STOP')], default='1', max_length=1)),
                ('datetime', models.DateTimeField()),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.shift')),
            ],
        ),
    ]
