# Generated by Django 3.2.6 on 2021-09-11 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_remove_additionalexpensecategory_is_accounting_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalexpense',
            name='calculation_formula',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.calculationformula'),
        ),
        migrations.AddField(
            model_name='calculationformula',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
