# Generated by Django 3.2.6 on 2021-08-20 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_auto_20210820_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shifttimer',
            old_name='timer_type',
            new_name='action',
        ),
    ]
