# Generated by Django 3.2.6 on 2021-09-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_auto_20210911_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalexpensecategory',
            name='calculation_formula',
        ),
    ]
