# Generated by Django 3.2.6 on 2021-09-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_remove_additionalexpensecategory_calculation_formula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalexpense',
            name='datetime',
        ),
        migrations.AddField(
            model_name='additionalexpense',
            name='created_at_time',
            field=models.TimeField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='additionalexpense',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
