# Generated by Django 3.2.6 on 2021-08-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_rename_timer_type_shifttimer_action'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShiftTimer',
            new_name='ShiftTraker',
        ),
    ]
