# Generated by Django 3.2.6 on 2021-09-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_auto_20210911_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalexpense',
            name='sum',
            field=models.IntegerField(null=True),
        ),
    ]
