# Generated by Django 3.2.6 on 2021-08-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_rename_shifttimer_shifttraker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='cash_start',
            field=models.IntegerField(null=True),
        ),
    ]
