# Generated by Django 3.2.6 on 2021-09-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_alter_additionalexpense_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalexpense',
            name='sum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
