# Generated by Django 3.2.6 on 2021-09-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_alter_additionalexpense_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalexpense',
            name='calculation_formula',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='CalculationFormula',
        ),
    ]
